# Gradle
# Build using a Gradle wrapper script
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew' 
    tasks: 'build' # A list of tasks separated by spaces, such as 'build test'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
