springfox:
  documentation:
    swagger-ui:
      enabled: true

server:
  port: 8089
  servlet:
    context-path: /easyinsurance

spring:
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: teste2
  h2:
    console:
      enabled: true
      path: "/h2" 